from __future__ import annotations

import sqlite3
from pathlib import Path

import pandas as pd

DB_PATH = Path("data_pipeline/data/books.db")
CLEANED_PATH = Path("data_pipeline/data/cleaned_books.csv")
SQL_DIR = Path("data_pipeline/sql")
OUT_DIR = Path("data_pipeline/outputs")

QUERIES = {
    "01_where_between": """SELECT title, price_gbp, price_inr, rating FROM books WHERE in_stock = 1 AND price_gbp BETWEEN 10 AND 30 ORDER BY price_gbp DESC;""",
    "02_order_limit": """SELECT title, price_inr, rating FROM books ORDER BY price_inr DESC LIMIT 10;""",
    "03_distinct_categories": """SELECT DISTINCT category_name FROM categories ORDER BY category_name;""",
    "04_in_ratings": """SELECT title, rating, in_stock FROM books WHERE rating IN (4, 5) ORDER BY rating DESC, title LIMIT 15;""",
    "05_join_top3_each_category": """WITH ranked AS (\n    SELECT b.book_id, b.title, b.rating, b.price_inr, c.category_name,\n           ROW_NUMBER() OVER (PARTITION BY c.category_name ORDER BY b.rating DESC, b.price_inr DESC, b.title) AS rank_in_category\n    FROM books b\n    JOIN categories c ON b.category_id = c.category_id\n)\nSELECT category_name, title, rating, price_inr, rank_in_category\nFROM ranked\nWHERE rank_in_category <= 3\nORDER BY category_name, rank_in_category;""",
    "06_stock_summary": """SELECT c.category_name, COUNT(*) AS book_count, SUM(b.in_stock) AS in_stock_count, ROUND(AVG(b.price_inr), 2) AS avg_price_inr FROM books b JOIN categories c ON b.category_id=c.category_id GROUP BY c.category_name ORDER BY avg_price_inr DESC;""",
}


def create_schema(conn: sqlite3.Connection) -> None:
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(
        """
        DROP TABLE IF EXISTS books;
        DROP TABLE IF EXISTS categories;
        CREATE TABLE categories (
            category_id INTEGER PRIMARY KEY,
            category_name TEXT NOT NULL UNIQUE
        );
        CREATE TABLE books (
            book_id INTEGER PRIMARY KEY,
            title TEXT NOT NULL,
            price_gbp REAL NOT NULL,
            price_inr REAL NOT NULL,
            rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
            in_stock INTEGER NOT NULL CHECK (in_stock IN (0, 1)),
            category_id INTEGER NOT NULL REFERENCES categories(category_id)
        );
        CREATE INDEX idx_books_category ON books(category_id);
        CREATE INDEX idx_books_rating ON books(rating);
        """
    )


def load_dataframe(conn: sqlite3.Connection, df: pd.DataFrame) -> None:
    cats = pd.DataFrame({"category_name": sorted(df["category"].unique())})
    cats.to_sql("categories", conn, if_exists="append", index=False)
    mapping = pd.read_sql("SELECT category_id, category_name FROM categories", conn)
    merged = df.merge(mapping, left_on="category", right_on="category_name", how="left")
    books = merged.assign(in_stock=merged["in_stock"].astype(int)).loc[:, ["title", "price_gbp", "price_inr", "rating", "in_stock", "category_id"]]
    books.to_sql("books", conn, if_exists="append", index=False)


def execute_queries(conn: sqlite3.Connection) -> dict[str, pd.DataFrame]:
    SQL_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    result_frames: dict[str, pd.DataFrame] = {}
    markdown_parts = ["# SQL query outputs\n", "Generated by `load_and_query.py`. The six queries collectively cover SELECT/WHERE, ORDER BY, LIMIT, DISTINCT, BETWEEN/IN, and JOIN.\n"]
    for name, query in QUERIES.items():
        (SQL_DIR / f"{name}.sql").write_text(query + "\n", encoding="utf-8")
        frame = pd.read_sql(query, conn)
        result_frames[name] = frame
        markdown_parts.append(f"## {name}\n\n```sql\n{query}\n```\n\n```text\n{frame.to_string(index=False)}\n```\n")
    (OUT_DIR / "query_outputs.md").write_text("\n".join(markdown_parts), encoding="utf-8")
    return result_frames


def verify_pandas_equivalence(conn: sqlite3.Connection, cleaned: pd.DataFrame, sql_join: pd.DataFrame) -> None:
    cats = pd.read_sql("SELECT category_id, category_name FROM categories", conn)
    books = pd.read_sql("SELECT book_id, title, price_gbp, price_inr, rating, in_stock, category_id FROM books", conn)
    merged = books.merge(cats, on="category_id", how="inner")
    merged = merged.sort_values(["category_name", "rating", "price_inr", "title"], ascending=[True, False, False, True])
    merged["rank_in_category"] = merged.groupby("category_name").cumcount() + 1
    pandas_join = merged.loc[merged["rank_in_category"] <= 3, ["category_name", "title", "rating", "price_inr", "rank_in_category"]]
    pandas_join = pandas_join.sort_values(["category_name", "rank_in_category"]).reset_index(drop=True)
    sql_norm = sql_join[["category_name", "title", "rating", "price_inr", "rank_in_category"]].sort_values(["category_name", "rank_in_category"]).reset_index(drop=True)
    pd.testing.assert_frame_equal(sql_norm, pandas_join, check_dtype=False, check_exact=False, rtol=1e-12, atol=1e-12)

    examples = {
        "pd_read_sql_where": pd.read_sql(QUERIES["01_where_between"], conn),
        "pd_read_sql_limit": pd.read_sql(QUERIES["02_order_limit"], conn),
        "pd_merge_join_equivalent": pandas_join,
        "sql_join_result": sql_norm,
    }
    text = "# Pandas validation\n\nAll `pd.read_sql`/`pd.merge` checks passed.\n\n## pd.read_sql: WHERE + BETWEEN\n\n```text\n" + examples["pd_read_sql_where"].to_string(index=False) + "\n```\n\n## pd.read_sql: ORDER BY + LIMIT\n\n```text\n" + examples["pd_read_sql_limit"].to_string(index=False) + "\n```\n\n## pd.merge reproduction of JOIN\n\n```text\n" + pandas_join.to_string(index=False) + "\n```\n\n## SQL JOIN result\n\n```text\n" + sql_norm.to_string(index=False) + "\n```\n"
    (OUT_DIR / "pandas_validation.md").write_text(text, encoding="utf-8")


def run(cleaned_path: Path = CLEANED_PATH, db_path: Path = DB_PATH) -> None:
    df = pd.read_csv(cleaned_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()
    with sqlite3.connect(db_path) as conn:
        create_schema(conn)
        load_dataframe(conn, df)
        frames = execute_queries(conn)
        verify_pandas_equivalence(conn, df, frames["05_join_top3_each_category"])
        count = conn.execute("SELECT COUNT(*) FROM books").fetchone()[0]
        categories = conn.execute("SELECT COUNT(*) FROM categories").fetchone()[0]
        assert count >= 60, f"Expected >=60 books, found {count}"
        assert categories >= 3, f"Expected >=3 categories, found {categories}"
        print(f"Loaded {count} books across {categories} categories into {db_path}")


if __name__ == "__main__":
    run()
